#!/bin/sh
###################################################################################################
# ABCD study, Downloading data                                                             #
# Harri Merisaari, Ashmeet Jolly
###################################################################################################

selectionfile=$1 #assigns the value of the first command-line argument to this variable

if [ -z "$selectionfile" ] #checks if this variable is empty using the -z conditional expression, and if it is empty, the script prints an error message and exits with a status code of 1
then
    echo "Namelist file was not given"
    exit 1
fi

site="G010"
output_dir="/scratch/project_2001640/ABCD_fMRI/${site}_download/image03"
existing_subjects=() #an empty array to store existing subjects

if [ ! -d "$output_dir" ]; then
   mkdir -p $output_dir
fi

#ls -1 "$output_dir/"

#check for existing subjects in the output directory
for file in $(ls -1 $output_dir/ | grep .tgz); do  #iterates over each file in the output directory
    #echo $file

    filename=$(basename "$file") #extracts the filename from the file path using basename and assigns it to the filename variable
    subject="${filename:0:15}"  # Extract the first 15 characters from the filename
    existing_subjects+=("$subject")
done

no_of_subjects=$(wc -l $selectionfile | awk '{print $1}') #counts the number of lines in the selectionfile using wc command and extracts the number using awk
echo $no_of_subjects " subjects to be processed"

source '/projappl/project_2001640/ABCD_fMRI_SW/env/bin/activate'

#create a variable to store the successful and failed subjects
successful_subjects=''
failed_subjects=''

date_run=$(/usr/bin/date '+Year+%Y_Month%m_Day%d_H%H_M%M_S%S') #record the date of run
start_time=$(/usr/bin/date +%s) #record the start time in seconds

#go through lines in the selection file
for round in $(seq $no_of_subjects)
do
    src_subject_id=$(sed -n "$round"p $selectionfile | awk '{print $1}') #extracts src_subject_id from the selection file by retrieving the value in the first column of the corresponding line using sed and awk commands
    mri_info_visitid=$(sed -n "$round"p $selectionfile | awk '{print $2}')
    eventname=$(sed -n "$round"p $selectionfile | awk '{print $3}')

   # check if subject  already exists in the output directory
    subject_exists=false
    for existing_subject in "${existing_subjects[@]}"; do
        if [[ $existing_subject == NDAR$src_subject_id ]]; then
            subject_exists=true
	    break
        fi
    done

    if $subject_exists; then
       echo "Subject NDAR$src_subject_id already exists. Skipping download."
       echo "Subject NDAR$src_subject_id already exists. Skipping download."  >> ./downcmd_txt_files/${date_run}_downcmd_log.txt #gives you log about what files have been downloaded, and this log is generated by the NDA
       continue
    fi

    cmd=$(echo downloadcmd -d /scratch/project_2001640/ABCD_fMRI/${site}_download -dp 1225427 -u jollya --file-regex NDAR$src_subject_id)
    echo "Processing subject: $src_subject_id"

    #Measure the execution time for the command
    start_cmd=$(/usr/bin/date +%s)
    ret=$(eval $cmd) #this is the command that actually runs the $cmd
    if [ "$?" -eq "0" ]; then
	echo "Success: $src_subject_id"
	successful_subjects+="$src_subject_id passed\n"
    else
	echo "Failure: $src_subject_id"
	failed_subjects+="$src_subject_id failed \n"
    fi
    echo $ret >>  ./downcmd_txt_files/${date_run}_downcmd_log.txt #gives you log about what files have been downloaded, and this log is generated by the NDA
    end_cmd=$(/usr/bin/date +%s)
    execution_time=$((end_cmd - start_cmd))


    echo "Subject ID: $src_subject_id, Execution time: $execution_time seconds" >>  ./downcmd_txt_files/${date_run}_execution.txt
done
end_time=$(/usr/bin/date +%s) #Record the end time in seconds
total_execution_time=$((end_time - start_time))

#Write the results to a text file
echo -e "Subject ID\tStatus" >  ./downcmd_txt_files/${date_run}_results.txt
echo -e "$successful_subjects$failed_subjects" >>  ./downcmd_txt_files/${date_run}_results.txt
echo "Total execution time: $((total_execution_time)) seconds" >> ./downcmd_txt_files/${date_run}_results.txt
